[package]
name = "svutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# (Here's how you consume it from other modules)
# [dependencies]
# svutils = { path = "../vutils" }
